# File: .github/workflows/repo-sync.yml
name: 同步 jdsign
on:
  schedule:
    - cron: '1 0,15 * * *'
  workflow_dispatch:
  watch:
    types: started
  repository_dispatch:
    types: Sync_Actions_smzdm
jobs:
  repo-sync:
    env:
      PAT: ${{ secrets.PAT }} #此处PAT需要申请，教程详见：https://www.jianshu.com/p/bb82b3ad1d11
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: sync Actions_smzdm
        uses: repo-sync/github-sync@v2
        if: env.PAT
        with:
          source_repo: "https://github.com/ruicky/jd_sign_bot.git"
          source_branch: "master"
          destination_branch: "master"
          github_token: ${{ secrets.PAT }}
